language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.502

services:
  - docker

script:
  - dotnet restore ./Source/Patchup.sln
  - dotnet build ./Source/Patchup.sln
  - dotnet test ./Source/Diff.Tests/Diff.Tests.csproj
  - dotnet test ./Source/Patchup.Tests/Patchup.Tests.csproj

