language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.502

before_install:
- chmod +x ./build.sh
- chmod +x ./test.sh
- chmod +x ./deploy.sh

script:
- ./build.sh
- ./test.sh

services:
- docker

