language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.502

before_install:
- chmod +x ./Scripts/build.sh
- chmod +x ./Scripts/test.sh
- chmod +x ./Scripts/deploy.sh

script:
- ./Scripts/build.sh
- ./Scripts/test.sh

services:
- docker

